### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Johnanhenry** [avistnm/Metasploit-avistnm#1]
msfvenom                                             Traceback (most recent call last):                     ruby: No such file or directory -- /data/data/com.termux/files/home/metasploit-framework/msfvenom (LoadError) $

**Comment by avistnm** [comment]
Give me the full screen shot of the error

**Comment by avistnm** [comment]
> msfvenom                                             Traceback (most recent call last):                     ruby: No such file or directory -- /data/data/com.termux/files/home/metasploit-framework/msfvenom (LoadError) $
> 

Send screen shot then i could try to help you

**Comment by Gregnald** [comment]
@Johnanhenry  Send Screen shot of the issue the I coulde help along with the commanf you entered

**Comment by Gregnald** [comment]
@Johnanhenry if u will not reply then I will have to close this session.............

**Comment by Johnanhenry** [comment]
I fixed it with a different command.

**Comment by Gregnald** [comment]
Ok then thanks for using this metasploit @Johnanhenry
