### ISSUE TITLE
Is this repo still active 

### ISSUE THREAD

**Issue by ChillVibesMushroom** [avistnm/Metasploit-avistnm#3]
Followed the install instructions

msfconsole
Could not find rake-13.0.3 in any of the sources
Run `bundle install` to install missing gems.

~ $ bundle install                                                                      
Could not load OpenSSL.                                                                 You must recompile Ruby with OpenSSL support or change the sources in your Gemfile from 'https' to 'http'. Instructions for compiling with OpenSSL using RVM are available at   https://rvm.io/packages/openssl.

**Comment by Gregnald** [comment]
Sorry but the project is discontinued
